language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 8.0
      env: FRAMEWORK_VERSION=laravel/framework:8.*
    - php: 8.1
      env: FRAMEWORK_VERSION=laravel/framework:8.*

before_install:
  - phpenv config-rm xdebug.ini || true

before_script:
  - composer require "${FRAMEWORK_VERSION}" --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --no-suggest --optimize-autoloader

script:
  - vendor/bin/phpunit
